### ISSUE TITLE
Web Connect: Invalid password for user: 3c9073...

### ISSUE THREAD

**Issue by mike1573** [karser/EasyQuickImport#1]
Keep getting invalid password in Web Connect after importing the .qwc file and setting the password an schedule.

**Comment by karser** [comment]
Have you watched this video? https://www.youtube.com/watch?v=6kVJrthCQr0

Did you follow these steps?
1. Set a new password when creating a new company in EasyQuickImport
2. Enter this password when importing the file into the Web Connector

If nothing helps, can you please tell me what QB version do you have and attach the logs (click view log in web connector)?
Are you using cloud or self-hosted EasyQuickImport?

**Comment by karser** [comment]
Feel free to re-open if you still have this issue
