### ISSUE TITLE
How to download converted QUICKBOOK format

### ISSUE THREAD

**Issue by chenster** [karser/EasyQuickImport#3]
Is there a way to download converted Quickbook .qbo for manual import (without web connector), In case of missing web connector?

**Comment by karser** [comment]
Hello. What is .qbo? Is it a QuickBooks Online Statement file? Please tell me more about your use case.

**Comment by chenster** [comment]
Yes quickbook online format. It needs to be uploaded manually.

**Comment by karser** [comment]
Isn't migration from qbo to desktop supported out of the box by Intuit? Found [this](https://quickbooks.intuit.com/learn-support/en-us/help-article/import-export-data-files/export-convert-quickbooks-online-data-quickbooks/L0tKtLwhn_US_en_US) for example.

**Comment by chenster** [comment]
I misspoke, it's Quickbooks bank statement format, sometime do need to download and import that way
https://quickbooks.intuit.com/learn-support/en-us/help-article/banking/file-types-extensions-used-quickbooks-desktop/L3vuO2X4c_US_en_US

**Comment by karser** [comment]
Got it. You download the .qbo file from your online banking, correct? But there is said, "You can import a QBO file to quickly get transactions into your bank register.".  Isn't it a built-in QBD functionality?
