### ISSUE TITLE
Autofill data

### ISSUE THREAD

**Issue by MrEinstin** [karser/EasyQuickImport#5]
When creating the import spreadsheet for invoices, do I have to provide ALL of the import information that is needed on the invoice? For example, can I just provide the customer account number and it merge the other customer data such as the account name and address? Same example for the billed line item. If I just provide the item code will it fill in the description and the rate?

Thanks in advance.

**Comment by MrEinstin** [comment]
Apparently the importer has issues with later versions of MS Excell. Caused 500 internal server error. However saving as comma delimited csv I was able to get to the mapping stage. I couldn't go any further though since my available fields do not match with your hard coded import fields.

**Comment by karser** [comment]
Hello. Sorry for the late reply. Those fields are not hardcoded - you can map them as you can see on this screenshot
![image](https://github.com/karser/EasyQuickImport/assets/1675033/f7d98545-8b3c-41af-8717-37090cfd1c17)
More info on the video https://www.youtube.com/watch?v=ZKe002JUIww
